### ISSUE TITLE
Could you provide model file and preprocessing file

### ISSUE THREAD

**Issue by Sere1nz** [DigCS/Luna-16-nodules-volume#1]
Could you provide model file and preprocessing file?
the performance is pretty good ,and have you tested on the original full size image?

**Comment by DigCS** [comment]
> Could you provide model file and preprocessing file? the performance is pretty good ,and have you tested on the original full size image?

Hello, due to the relevance of the next steps in research with some team members, the code will be partially uploaded after thorough discussion with everyone.

The model has only been tested on cropped images so far. Currently, using cropped images is a method employed by several researchers in various competitions, as it preserves the detailed information of the Region of Interest (ROI). Additionally, due to the large size of the original images, using the 3D segmentation method would require high hardware specifications and severely impact training efficiency. Therefore, we did not use the original size images.
